spring:
  zipkin:
    baseUrl: http://localhost:9411

eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    ROOT: DEBUG
    com.masoud.gateway: DEBUG