eureka:
  instance:
    hostname: config-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    ROOT: DEBUG
    com.masoud.accountmanagement: DEBUG