spring:
  zipkin:
    baseUrl: http://localhost:9411
  devtools:
    restart:
      enabled: true
      additional-exclude: .h2.server.properties
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/accountmanagement;DB_CLOSE_DELAY=-1
    username: accountManagement
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
      path: /h2

eureka:
  instance:
    hostname: account-management
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    ROOT: DEBUG
    com.masoud.accountmanagement: DEBUG